# Generated by Django 4.0.4 on 2022-04-26 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('package', models.CharField(choices=[('S', 'Minor Tune Up'), ('M', 'Moderate Tune Up'), ('F', 'Full Tune Up')], default='S', max_length=1)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.board')),
            ],
        ),
    ]
