# Generated by Django 4.0.4 on 2022-04-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tuning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuning',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='tuning',
            name='date',
            field=models.DateField(verbose_name='Tuning Date'),
        ),
    ]
