# Generated by Django 4.0.4 on 2022-04-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_bindings_board_bindings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='bindings',
        ),
        migrations.DeleteModel(
            name='Bindings',
        ),
    ]
