# Generated by Django 4.0.4 on 2022-04-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_board_bindings_delete_bindings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bindings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='bindings',
            field=models.ManyToManyField(to='main_app.bindings'),
        ),
    ]
